/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: configs.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "configs.pb-c.h"
void   enb_config_request__init
                     (EnbConfigRequest         *message)
{
  static EnbConfigRequest init_value = ENB_CONFIG_REQUEST__INIT;
  *message = init_value;
}
size_t enb_config_request__get_packed_size
                     (const EnbConfigRequest *message)
{
  assert(message->base.descriptor == &enb_config_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t enb_config_request__pack
                     (const EnbConfigRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &enb_config_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t enb_config_request__pack_to_buffer
                     (const EnbConfigRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &enb_config_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EnbConfigRequest *
       enb_config_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EnbConfigRequest *)
     protobuf_c_message_unpack (&enb_config_request__descriptor,
                                allocator, len, data);
}
void   enb_config_request__free_unpacked
                     (EnbConfigRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &enb_config_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ue_config_request__init
                     (UeConfigRequest         *message)
{
  static UeConfigRequest init_value = UE_CONFIG_REQUEST__INIT;
  *message = init_value;
}
size_t ue_config_request__get_packed_size
                     (const UeConfigRequest *message)
{
  assert(message->base.descriptor == &ue_config_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ue_config_request__pack
                     (const UeConfigRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ue_config_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ue_config_request__pack_to_buffer
                     (const UeConfigRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ue_config_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UeConfigRequest *
       ue_config_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UeConfigRequest *)
     protobuf_c_message_unpack (&ue_config_request__descriptor,
                                allocator, len, data);
}
void   ue_config_request__free_unpacked
                     (UeConfigRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ue_config_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sg_info_msg__init
                     (SgInfoMsg         *message)
{
  static SgInfoMsg init_value = SG_INFO_MSG__INIT;
  *message = init_value;
}
size_t sg_info_msg__get_packed_size
                     (const SgInfoMsg *message)
{
  assert(message->base.descriptor == &sg_info_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sg_info_msg__pack
                     (const SgInfoMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sg_info_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sg_info_msg__pack_to_buffer
                     (const SgInfoMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sg_info_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SgInfoMsg *
       sg_info_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SgInfoMsg *)
     protobuf_c_message_unpack (&sg_info_msg__descriptor,
                                allocator, len, data);
}
void   sg_info_msg__free_unpacked
                     (SgInfoMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sg_info_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sg_info_config__init
                     (SgInfoConfig         *message)
{
  static SgInfoConfig init_value = SG_INFO_CONFIG__INIT;
  *message = init_value;
}
size_t sg_info_config__get_packed_size
                     (const SgInfoConfig *message)
{
  assert(message->base.descriptor == &sg_info_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sg_info_config__pack
                     (const SgInfoConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sg_info_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sg_info_config__pack_to_buffer
                     (const SgInfoConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sg_info_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SgInfoConfig *
       sg_info_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SgInfoConfig *)
     protobuf_c_message_unpack (&sg_info_config__descriptor,
                                allocator, len, data);
}
void   sg_info_config__free_unpacked
                     (SgInfoConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sg_info_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cell_phy_config__init
                     (CellPhyConfig         *message)
{
  static CellPhyConfig init_value = CELL_PHY_CONFIG__INIT;
  *message = init_value;
}
size_t cell_phy_config__get_packed_size
                     (const CellPhyConfig *message)
{
  assert(message->base.descriptor == &cell_phy_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cell_phy_config__pack
                     (const CellPhyConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cell_phy_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cell_phy_config__pack_to_buffer
                     (const CellPhyConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cell_phy_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CellPhyConfig *
       cell_phy_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CellPhyConfig *)
     protobuf_c_message_unpack (&cell_phy_config__descriptor,
                                allocator, len, data);
}
void   cell_phy_config__free_unpacked
                     (CellPhyConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cell_phy_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cell_mac_config__init
                     (CellMacConfig         *message)
{
  static CellMacConfig init_value = CELL_MAC_CONFIG__INIT;
  *message = init_value;
}
size_t cell_mac_config__get_packed_size
                     (const CellMacConfig *message)
{
  assert(message->base.descriptor == &cell_mac_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cell_mac_config__pack
                     (const CellMacConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cell_mac_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cell_mac_config__pack_to_buffer
                     (const CellMacConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cell_mac_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CellMacConfig *
       cell_mac_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CellMacConfig *)
     protobuf_c_message_unpack (&cell_mac_config__descriptor,
                                allocator, len, data);
}
void   cell_mac_config__free_unpacked
                     (CellMacConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cell_mac_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cell_rrc_config__init
                     (CellRrcConfig         *message)
{
  static CellRrcConfig init_value = CELL_RRC_CONFIG__INIT;
  *message = init_value;
}
size_t cell_rrc_config__get_packed_size
                     (const CellRrcConfig *message)
{
  assert(message->base.descriptor == &cell_rrc_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cell_rrc_config__pack
                     (const CellRrcConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cell_rrc_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cell_rrc_config__pack_to_buffer
                     (const CellRrcConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cell_rrc_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CellRrcConfig *
       cell_rrc_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CellRrcConfig *)
     protobuf_c_message_unpack (&cell_rrc_config__descriptor,
                                allocator, len, data);
}
void   cell_rrc_config__free_unpacked
                     (CellRrcConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cell_rrc_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cell_config__init
                     (CellConfig         *message)
{
  static CellConfig init_value = CELL_CONFIG__INIT;
  *message = init_value;
}
size_t cell_config__get_packed_size
                     (const CellConfig *message)
{
  assert(message->base.descriptor == &cell_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cell_config__pack
                     (const CellConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cell_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cell_config__pack_to_buffer
                     (const CellConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cell_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CellConfig *
       cell_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CellConfig *)
     protobuf_c_message_unpack (&cell_config__descriptor,
                                allocator, len, data);
}
void   cell_config__free_unpacked
                     (CellConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cell_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   enb_config_reply__init
                     (EnbConfigReply         *message)
{
  static EnbConfigReply init_value = ENB_CONFIG_REPLY__INIT;
  *message = init_value;
}
size_t enb_config_reply__get_packed_size
                     (const EnbConfigReply *message)
{
  assert(message->base.descriptor == &enb_config_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t enb_config_reply__pack
                     (const EnbConfigReply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &enb_config_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t enb_config_reply__pack_to_buffer
                     (const EnbConfigReply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &enb_config_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EnbConfigReply *
       enb_config_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EnbConfigReply *)
     protobuf_c_message_unpack (&enb_config_reply__descriptor,
                                allocator, len, data);
}
void   enb_config_reply__free_unpacked
                     (EnbConfigReply *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &enb_config_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   drx_config__init
                     (DrxConfig         *message)
{
  static DrxConfig init_value = DRX_CONFIG__INIT;
  *message = init_value;
}
size_t drx_config__get_packed_size
                     (const DrxConfig *message)
{
  assert(message->base.descriptor == &drx_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t drx_config__pack
                     (const DrxConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &drx_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t drx_config__pack_to_buffer
                     (const DrxConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &drx_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DrxConfig *
       drx_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DrxConfig *)
     protobuf_c_message_unpack (&drx_config__descriptor,
                                allocator, len, data);
}
void   drx_config__free_unpacked
                     (DrxConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &drx_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sps_config__init
                     (SpsConfig         *message)
{
  static SpsConfig init_value = SPS_CONFIG__INIT;
  *message = init_value;
}
size_t sps_config__get_packed_size
                     (const SpsConfig *message)
{
  assert(message->base.descriptor == &sps_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sps_config__pack
                     (const SpsConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sps_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sps_config__pack_to_buffer
                     (const SpsConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sps_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SpsConfig *
       sps_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SpsConfig *)
     protobuf_c_message_unpack (&sps_config__descriptor,
                                allocator, len, data);
}
void   sps_config__free_unpacked
                     (SpsConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sps_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sr_config__init
                     (SrConfig         *message)
{
  static SrConfig init_value = SR_CONFIG__INIT;
  *message = init_value;
}
size_t sr_config__get_packed_size
                     (const SrConfig *message)
{
  assert(message->base.descriptor == &sr_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sr_config__pack
                     (const SrConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sr_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sr_config__pack_to_buffer
                     (const SrConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sr_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SrConfig *
       sr_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SrConfig *)
     protobuf_c_message_unpack (&sr_config__descriptor,
                                allocator, len, data);
}
void   sr_config__free_unpacked
                     (SrConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sr_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cqi_config__init
                     (CqiConfig         *message)
{
  static CqiConfig init_value = CQI_CONFIG__INIT;
  *message = init_value;
}
size_t cqi_config__get_packed_size
                     (const CqiConfig *message)
{
  assert(message->base.descriptor == &cqi_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cqi_config__pack
                     (const CqiConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cqi_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cqi_config__pack_to_buffer
                     (const CqiConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cqi_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CqiConfig *
       cqi_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CqiConfig *)
     protobuf_c_message_unpack (&cqi_config__descriptor,
                                allocator, len, data);
}
void   cqi_config__free_unpacked
                     (CqiConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cqi_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ue_capabilities__init
                     (UeCapabilities         *message)
{
  static UeCapabilities init_value = UE_CAPABILITIES__INIT;
  *message = init_value;
}
size_t ue_capabilities__get_packed_size
                     (const UeCapabilities *message)
{
  assert(message->base.descriptor == &ue_capabilities__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ue_capabilities__pack
                     (const UeCapabilities *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ue_capabilities__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ue_capabilities__pack_to_buffer
                     (const UeCapabilities *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ue_capabilities__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UeCapabilities *
       ue_capabilities__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UeCapabilities *)
     protobuf_c_message_unpack (&ue_capabilities__descriptor,
                                allocator, len, data);
}
void   ue_capabilities__free_unpacked
                     (UeCapabilities *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ue_capabilities__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scell_config__init
                     (ScellConfig         *message)
{
  static ScellConfig init_value = SCELL_CONFIG__INIT;
  *message = init_value;
}
size_t scell_config__get_packed_size
                     (const ScellConfig *message)
{
  assert(message->base.descriptor == &scell_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scell_config__pack
                     (const ScellConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scell_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scell_config__pack_to_buffer
                     (const ScellConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scell_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScellConfig *
       scell_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScellConfig *)
     protobuf_c_message_unpack (&scell_config__descriptor,
                                allocator, len, data);
}
void   scell_config__free_unpacked
                     (ScellConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &scell_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ue_phy_config__init
                     (UePhyConfig         *message)
{
  static UePhyConfig init_value = UE_PHY_CONFIG__INIT;
  *message = init_value;
}
size_t ue_phy_config__get_packed_size
                     (const UePhyConfig *message)
{
  assert(message->base.descriptor == &ue_phy_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ue_phy_config__pack
                     (const UePhyConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ue_phy_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ue_phy_config__pack_to_buffer
                     (const UePhyConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ue_phy_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UePhyConfig *
       ue_phy_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UePhyConfig *)
     protobuf_c_message_unpack (&ue_phy_config__descriptor,
                                allocator, len, data);
}
void   ue_phy_config__free_unpacked
                     (UePhyConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ue_phy_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ue_mac_config__init
                     (UeMacConfig         *message)
{
  static UeMacConfig init_value = UE_MAC_CONFIG__INIT;
  *message = init_value;
}
size_t ue_mac_config__get_packed_size
                     (const UeMacConfig *message)
{
  assert(message->base.descriptor == &ue_mac_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ue_mac_config__pack
                     (const UeMacConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ue_mac_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ue_mac_config__pack_to_buffer
                     (const UeMacConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ue_mac_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UeMacConfig *
       ue_mac_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UeMacConfig *)
     protobuf_c_message_unpack (&ue_mac_config__descriptor,
                                allocator, len, data);
}
void   ue_mac_config__free_unpacked
                     (UeMacConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ue_mac_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ue_rrc_config__init
                     (UeRrcConfig         *message)
{
  static UeRrcConfig init_value = UE_RRC_CONFIG__INIT;
  *message = init_value;
}
size_t ue_rrc_config__get_packed_size
                     (const UeRrcConfig *message)
{
  assert(message->base.descriptor == &ue_rrc_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ue_rrc_config__pack
                     (const UeRrcConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ue_rrc_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ue_rrc_config__pack_to_buffer
                     (const UeRrcConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ue_rrc_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UeRrcConfig *
       ue_rrc_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UeRrcConfig *)
     protobuf_c_message_unpack (&ue_rrc_config__descriptor,
                                allocator, len, data);
}
void   ue_rrc_config__free_unpacked
                     (UeRrcConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ue_rrc_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ue_config__init
                     (UeConfig         *message)
{
  static UeConfig init_value = UE_CONFIG__INIT;
  *message = init_value;
}
size_t ue_config__get_packed_size
                     (const UeConfig *message)
{
  assert(message->base.descriptor == &ue_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ue_config__pack
                     (const UeConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ue_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ue_config__pack_to_buffer
                     (const UeConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ue_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UeConfig *
       ue_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UeConfig *)
     protobuf_c_message_unpack (&ue_config__descriptor,
                                allocator, len, data);
}
void   ue_config__free_unpacked
                     (UeConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ue_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ue_config_reply__init
                     (UeConfigReply         *message)
{
  static UeConfigReply init_value = UE_CONFIG_REPLY__INIT;
  *message = init_value;
}
size_t ue_config_reply__get_packed_size
                     (const UeConfigReply *message)
{
  assert(message->base.descriptor == &ue_config_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ue_config_reply__pack
                     (const UeConfigReply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ue_config_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ue_config_reply__pack_to_buffer
                     (const UeConfigReply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ue_config_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UeConfigReply *
       ue_config_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UeConfigReply *)
     protobuf_c_message_unpack (&ue_config_reply__descriptor,
                                allocator, len, data);
}
void   ue_config_reply__free_unpacked
                     (UeConfigReply *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ue_config_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   configs__init
                     (Configs         *message)
{
  static Configs init_value = CONFIGS__INIT;
  *message = init_value;
}
size_t configs__get_packed_size
                     (const Configs *message)
{
  assert(message->base.descriptor == &configs__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t configs__pack
                     (const Configs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &configs__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t configs__pack_to_buffer
                     (const Configs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &configs__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Configs *
       configs__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Configs *)
     protobuf_c_message_unpack (&configs__descriptor,
                                allocator, len, data);
}
void   configs__free_unpacked
                     (Configs *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &configs__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor enb_config_request__field_descriptors[2] =
{
  {
    "layer",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(EnbConfigRequest, has_layer),
    offsetof(EnbConfigRequest, layer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cc_id",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(EnbConfigRequest, n_cc_id),
    offsetof(EnbConfigRequest, cc_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned enb_config_request__field_indices_by_name[] = {
  1,   /* field[1] = cc_id */
  0,   /* field[0] = layer */
};
static const ProtobufCIntRange enb_config_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor enb_config_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "enb_config_request",
  "EnbConfigRequest",
  "EnbConfigRequest",
  "",
  sizeof(EnbConfigRequest),
  2,
  enb_config_request__field_descriptors,
  enb_config_request__field_indices_by_name,
  1,  enb_config_request__number_ranges,
  (ProtobufCMessageInit) enb_config_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ue_config_request__field_descriptors[2] =
{
  {
    "layer",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeConfigRequest, has_layer),
    offsetof(UeConfigRequest, layer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rnti",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeConfigRequest, n_rnti),
    offsetof(UeConfigRequest, rnti),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ue_config_request__field_indices_by_name[] = {
  0,   /* field[0] = layer */
  1,   /* field[1] = rnti */
};
static const ProtobufCIntRange ue_config_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ue_config_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ue_config_request",
  "UeConfigRequest",
  "UeConfigRequest",
  "",
  sizeof(UeConfigRequest),
  2,
  ue_config_request__field_descriptors,
  ue_config_request__field_indices_by_name,
  1,  ue_config_request__number_ranges,
  (ProtobufCMessageInit) ue_config_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sg_info_msg__field_descriptors[2] =
{
  {
    "periodicity",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SgInfoMsg, has_periodicity),
    offsetof(SgInfoMsg, periodicity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SgInfoMsg, has_length),
    offsetof(SgInfoMsg, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sg_info_msg__field_indices_by_name[] = {
  1,   /* field[1] = length */
  0,   /* field[0] = periodicity */
};
static const ProtobufCIntRange sg_info_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sg_info_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sg_info_msg",
  "SgInfoMsg",
  "SgInfoMsg",
  "",
  sizeof(SgInfoMsg),
  2,
  sg_info_msg__field_descriptors,
  sg_info_msg__field_indices_by_name,
  1,  sg_info_msg__number_ranges,
  (ProtobufCMessageInit) sg_info_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sg_info_config__field_descriptors[4] =
{
  {
    "sfn",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SgInfoConfig, has_sfn),
    offsetof(SgInfoConfig, sfn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sib1_len",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SgInfoConfig, has_sib1_len),
    offsetof(SgInfoConfig, sib1_len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "si_window_len",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SgInfoConfig, has_si_window_len),
    offsetof(SgInfoConfig, si_window_len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "si_message",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SgInfoConfig, n_si_message),
    offsetof(SgInfoConfig, si_message),
    &sg_info_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sg_info_config__field_indices_by_name[] = {
  0,   /* field[0] = sfn */
  3,   /* field[3] = si_message */
  2,   /* field[2] = si_window_len */
  1,   /* field[1] = sib1_len */
};
static const ProtobufCIntRange sg_info_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor sg_info_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sg_info_config",
  "SgInfoConfig",
  "SgInfoConfig",
  "",
  sizeof(SgInfoConfig),
  4,
  sg_info_config__field_descriptors,
  sg_info_config__field_indices_by_name,
  1,  sg_info_config__number_ranges,
  (ProtobufCMessageInit) sg_info_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cell_phy_config__field_descriptors[21] =
{
  {
    "pci",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellPhyConfig, has_pci),
    offsetof(CellPhyConfig, pci),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cell_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellPhyConfig, has_cell_id),
    offsetof(CellPhyConfig, cell_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pusch_hopp_offset",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellPhyConfig, has_pusch_hopp_offset),
    offsetof(CellPhyConfig, pusch_hopp_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hopp_mode",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CellPhyConfig, has_hopp_mode),
    offsetof(CellPhyConfig, hopp_mode),
    &hopping_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_sb",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellPhyConfig, has_n_sb),
    offsetof(CellPhyConfig, n_sb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phich_res",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CellPhyConfig, has_phich_res),
    offsetof(CellPhyConfig, phich_res),
    &phich_resource__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phich_dur",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CellPhyConfig, has_phich_dur),
    offsetof(CellPhyConfig, phich_dur),
    &phich_duration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "init_nr_PDCCH_OFDM_sym",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellPhyConfig, has_init_nr_pdcch_ofdm_sym),
    offsetof(CellPhyConfig, init_nr_pdcch_ofdm_sym),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "si_conf",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CellPhyConfig, si_conf),
    &sg_info_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dl_bw",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellPhyConfig, has_dl_bw),
    offsetof(CellPhyConfig, dl_bw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ul_bw",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellPhyConfig, has_ul_bw),
    offsetof(CellPhyConfig, ul_bw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ul_cyc_prefix_len",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CellPhyConfig, has_ul_cyc_prefix_len),
    offsetof(CellPhyConfig, ul_cyc_prefix_len),
    &ul_cyclic_prefix_length__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dl_cyc_prefix_len",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CellPhyConfig, has_dl_cyc_prefix_len),
    offsetof(CellPhyConfig, dl_cyc_prefix_len),
    &dl_cyclic_prefix_length__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "antenna_ports_count",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellPhyConfig, has_antenna_ports_count),
    offsetof(CellPhyConfig, antenna_ports_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dupl_mode",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CellPhyConfig, has_dupl_mode),
    offsetof(CellPhyConfig, dupl_mode),
    &duplex_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prach_conf_index",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellPhyConfig, has_prach_conf_index),
    offsetof(CellPhyConfig, prach_conf_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prach_freq_offset",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellPhyConfig, has_prach_freq_offset),
    offsetof(CellPhyConfig, prach_freq_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ra_resp_window_size",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellPhyConfig, has_ra_resp_window_size),
    offsetof(CellPhyConfig, ra_resp_window_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n1PUCCH_AN",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellPhyConfig, has_n1pucch_an),
    offsetof(CellPhyConfig, n1pucch_an),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deltaPUCCH_shift",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellPhyConfig, has_deltapucch_shift),
    offsetof(CellPhyConfig, deltapucch_shift),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enable_64QAM",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CellPhyConfig, has_enable_64qam),
    offsetof(CellPhyConfig, enable_64qam),
    &qam__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cell_phy_config__field_indices_by_name[] = {
  13,   /* field[13] = antenna_ports_count */
  1,   /* field[1] = cell_id */
  19,   /* field[19] = deltaPUCCH_shift */
  9,   /* field[9] = dl_bw */
  12,   /* field[12] = dl_cyc_prefix_len */
  14,   /* field[14] = dupl_mode */
  20,   /* field[20] = enable_64QAM */
  3,   /* field[3] = hopp_mode */
  7,   /* field[7] = init_nr_PDCCH_OFDM_sym */
  18,   /* field[18] = n1PUCCH_AN */
  4,   /* field[4] = n_sb */
  0,   /* field[0] = pci */
  6,   /* field[6] = phich_dur */
  5,   /* field[5] = phich_res */
  15,   /* field[15] = prach_conf_index */
  16,   /* field[16] = prach_freq_offset */
  2,   /* field[2] = pusch_hopp_offset */
  17,   /* field[17] = ra_resp_window_size */
  8,   /* field[8] = si_conf */
  10,   /* field[10] = ul_bw */
  11,   /* field[11] = ul_cyc_prefix_len */
};
static const ProtobufCIntRange cell_phy_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 21 }
};
const ProtobufCMessageDescriptor cell_phy_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cell_phy_config",
  "CellPhyConfig",
  "CellPhyConfig",
  "",
  sizeof(CellPhyConfig),
  21,
  cell_phy_config__field_descriptors,
  cell_phy_config__field_indices_by_name,
  1,  cell_phy_config__number_ranges,
  (ProtobufCMessageInit) cell_phy_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cell_mac_config__field_descriptors[5] =
{
  {
    "sf_assign",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellMacConfig, has_sf_assign),
    offsetof(CellMacConfig, sf_assign),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "special_subframe_patterns",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellMacConfig, has_special_subframe_patterns),
    offsetof(CellMacConfig, special_subframe_patterns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac_cont_resol_timer",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellMacConfig, has_mac_cont_resol_timer),
    offsetof(CellMacConfig, mac_cont_resol_timer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_HARQ_Msg3Tx",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellMacConfig, has_max_harq_msg3tx),
    offsetof(CellMacConfig, max_harq_msg3tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nRB_cqi",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellMacConfig, has_nrb_cqi),
    offsetof(CellMacConfig, nrb_cqi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cell_mac_config__field_indices_by_name[] = {
  2,   /* field[2] = mac_cont_resol_timer */
  3,   /* field[3] = max_HARQ_Msg3Tx */
  4,   /* field[4] = nRB_cqi */
  0,   /* field[0] = sf_assign */
  1,   /* field[1] = special_subframe_patterns */
};
static const ProtobufCIntRange cell_mac_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor cell_mac_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cell_mac_config",
  "CellMacConfig",
  "CellMacConfig",
  "",
  sizeof(CellMacConfig),
  5,
  cell_mac_config__field_descriptors,
  cell_mac_config__field_indices_by_name,
  1,  cell_mac_config__number_ranges,
  (ProtobufCMessageInit) cell_mac_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cell_rrc_config__field_descriptors[6] =
{
  {
    "mbsfn_conf_rfperiod",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellRrcConfig, n_mbsfn_conf_rfperiod),
    offsetof(CellRrcConfig, mbsfn_conf_rfperiod),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mbsfn_conf_rfoffset",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellRrcConfig, n_mbsfn_conf_rfoffset),
    offsetof(CellRrcConfig, mbsfn_conf_rfoffset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mbsfn_conf_sfalloc",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellRrcConfig, n_mbsfn_conf_sfalloc),
    offsetof(CellRrcConfig, mbsfn_conf_sfalloc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "srs_sf_conf",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellRrcConfig, has_srs_sf_conf),
    offsetof(CellRrcConfig, srs_sf_conf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "srs_bw_conf",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellRrcConfig, has_srs_bw_conf),
    offsetof(CellRrcConfig, srs_bw_conf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "srs_max_up_pts",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellRrcConfig, has_srs_max_up_pts),
    offsetof(CellRrcConfig, srs_max_up_pts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cell_rrc_config__field_indices_by_name[] = {
  1,   /* field[1] = mbsfn_conf_rfoffset */
  0,   /* field[0] = mbsfn_conf_rfperiod */
  2,   /* field[2] = mbsfn_conf_sfalloc */
  4,   /* field[4] = srs_bw_conf */
  5,   /* field[5] = srs_max_up_pts */
  3,   /* field[3] = srs_sf_conf */
};
static const ProtobufCIntRange cell_rrc_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor cell_rrc_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cell_rrc_config",
  "CellRrcConfig",
  "CellRrcConfig",
  "",
  sizeof(CellRrcConfig),
  6,
  cell_rrc_config__field_descriptors,
  cell_rrc_config__field_indices_by_name,
  1,  cell_rrc_config__number_ranges,
  (ProtobufCMessageInit) cell_rrc_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cell_config__field_descriptors[4] =
{
  {
    "cc_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CellConfig, has_cc_id),
    offsetof(CellConfig, cc_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phy_conf",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CellConfig, phy_conf),
    &cell_phy_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac_conf",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CellConfig, mac_conf),
    &cell_mac_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rrc_conf",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CellConfig, rrc_conf),
    &cell_rrc_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cell_config__field_indices_by_name[] = {
  0,   /* field[0] = cc_id */
  2,   /* field[2] = mac_conf */
  1,   /* field[1] = phy_conf */
  3,   /* field[3] = rrc_conf */
};
static const ProtobufCIntRange cell_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor cell_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cell_config",
  "CellConfig",
  "CellConfig",
  "",
  sizeof(CellConfig),
  4,
  cell_config__field_descriptors,
  cell_config__field_indices_by_name,
  1,  cell_config__number_ranges,
  (ProtobufCMessageInit) cell_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor enb_config_reply__field_descriptors[1] =
{
  {
    "cell_conf",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EnbConfigReply, n_cell_conf),
    offsetof(EnbConfigReply, cell_conf),
    &cell_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned enb_config_reply__field_indices_by_name[] = {
  0,   /* field[0] = cell_conf */
};
static const ProtobufCIntRange enb_config_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor enb_config_reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "enb_config_reply",
  "EnbConfigReply",
  "EnbConfigReply",
  "",
  sizeof(EnbConfigReply),
  1,
  enb_config_reply__field_descriptors,
  enb_config_reply__field_indices_by_name,
  1,  enb_config_reply__number_ranges,
  (ProtobufCMessageInit) enb_config_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drx_config__field_descriptors[7] =
{
  {
    "on_dur_timer",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DrxConfig, has_on_dur_timer),
    offsetof(DrxConfig, on_dur_timer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drx_inact_timer",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DrxConfig, has_drx_inact_timer),
    offsetof(DrxConfig, drx_inact_timer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drx_retrx_timer",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DrxConfig, has_drx_retrx_timer),
    offsetof(DrxConfig, drx_retrx_timer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "long_drx_cycle",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DrxConfig, has_long_drx_cycle),
    offsetof(DrxConfig, long_drx_cycle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "long_drx_cycle_start_offset",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DrxConfig, has_long_drx_cycle_start_offset),
    offsetof(DrxConfig, long_drx_cycle_start_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "short_drx_cycle",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DrxConfig, has_short_drx_cycle),
    offsetof(DrxConfig, short_drx_cycle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drx_short_cycle_timer",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DrxConfig, has_drx_short_cycle_timer),
    offsetof(DrxConfig, drx_short_cycle_timer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drx_config__field_indices_by_name[] = {
  1,   /* field[1] = drx_inact_timer */
  2,   /* field[2] = drx_retrx_timer */
  6,   /* field[6] = drx_short_cycle_timer */
  3,   /* field[3] = long_drx_cycle */
  4,   /* field[4] = long_drx_cycle_start_offset */
  0,   /* field[0] = on_dur_timer */
  5,   /* field[5] = short_drx_cycle */
};
static const ProtobufCIntRange drx_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor drx_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "drx_config",
  "DrxConfig",
  "DrxConfig",
  "",
  sizeof(DrxConfig),
  7,
  drx_config__field_descriptors,
  drx_config__field_indices_by_name,
  1,  drx_config__number_ranges,
  (ProtobufCMessageInit) drx_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sps_config__field_descriptors[5] =
{
  {
    "sps_interval_ul",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SpsConfig, has_sps_interval_ul),
    offsetof(SpsConfig, sps_interval_ul),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sps_interval_dl",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SpsConfig, has_sps_interval_dl),
    offsetof(SpsConfig, sps_interval_dl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_conf_sps_proc",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SpsConfig, has_n_conf_sps_proc),
    offsetof(SpsConfig, n_conf_sps_proc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n1_PUCCH_AN_persistent_element",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SpsConfig, n_n1_pucch_an_persistent_element),
    offsetof(SpsConfig, n1_pucch_an_persistent_element),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "implicit_release_after",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SpsConfig, has_implicit_release_after),
    offsetof(SpsConfig, implicit_release_after),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sps_config__field_indices_by_name[] = {
  4,   /* field[4] = implicit_release_after */
  3,   /* field[3] = n1_PUCCH_AN_persistent_element */
  2,   /* field[2] = n_conf_sps_proc */
  1,   /* field[1] = sps_interval_dl */
  0,   /* field[0] = sps_interval_ul */
};
static const ProtobufCIntRange sps_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sps_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sps_config",
  "SpsConfig",
  "SpsConfig",
  "",
  sizeof(SpsConfig),
  5,
  sps_config__field_descriptors,
  sps_config__field_indices_by_name,
  1,  sps_config__number_ranges,
  (ProtobufCMessageInit) sps_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sr_config__field_descriptors[3] =
{
  {
    "sr_action",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SrConfig, has_sr_action),
    offsetof(SrConfig, sr_action),
    &setup_release_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sched_inter",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SrConfig, has_sched_inter),
    offsetof(SrConfig, sched_inter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dsr_trans_max",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SrConfig, has_dsr_trans_max),
    offsetof(SrConfig, dsr_trans_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sr_config__field_indices_by_name[] = {
  2,   /* field[2] = dsr_trans_max */
  1,   /* field[1] = sched_inter */
  0,   /* field[0] = sr_action */
};
static const ProtobufCIntRange sr_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sr_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sr_config",
  "SrConfig",
  "SrConfig",
  "",
  sizeof(SrConfig),
  3,
  sr_config__field_descriptors,
  sr_config__field_indices_by_name,
  1,  sr_config__number_ranges,
  (ProtobufCMessageInit) sr_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cqi_config__field_descriptors[3] =
{
  {
    "cqi_action",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CqiConfig, has_cqi_action),
    offsetof(CqiConfig, cqi_action),
    &setup_release_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cqi_sched_inter",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CqiConfig, has_cqi_sched_inter),
    offsetof(CqiConfig, cqi_sched_inter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ri_sched_inter",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CqiConfig, has_ri_sched_inter),
    offsetof(CqiConfig, ri_sched_inter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cqi_config__field_indices_by_name[] = {
  0,   /* field[0] = cqi_action */
  1,   /* field[1] = cqi_sched_inter */
  2,   /* field[2] = ri_sched_inter */
};
static const ProtobufCIntRange cqi_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cqi_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cqi_config",
  "CqiConfig",
  "CqiConfig",
  "",
  sizeof(CqiConfig),
  3,
  cqi_config__field_descriptors,
  cqi_config__field_indices_by_name,
  1,  cqi_config__number_ranges,
  (ProtobufCMessageInit) cqi_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ue_capabilities__field_descriptors[5] =
{
  {
    "half_duplex",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeCapabilities, has_half_duplex),
    offsetof(UeCapabilities, half_duplex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "intra_SF_hopping",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeCapabilities, has_intra_sf_hopping),
    offsetof(UeCapabilities, intra_sf_hopping),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type2_sb_1",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeCapabilities, has_type2_sb_1),
    offsetof(UeCapabilities, type2_sb_1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ue_category",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeCapabilities, has_ue_category),
    offsetof(UeCapabilities, ue_category),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "res_alloc_type1",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeCapabilities, has_res_alloc_type1),
    offsetof(UeCapabilities, res_alloc_type1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ue_capabilities__field_indices_by_name[] = {
  0,   /* field[0] = half_duplex */
  1,   /* field[1] = intra_SF_hopping */
  4,   /* field[4] = res_alloc_type1 */
  2,   /* field[2] = type2_sb_1 */
  3,   /* field[3] = ue_category */
};
static const ProtobufCIntRange ue_capabilities__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ue_capabilities__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ue_capabilities",
  "UeCapabilities",
  "UeCapabilities",
  "",
  sizeof(UeCapabilities),
  5,
  ue_capabilities__field_descriptors,
  ue_capabilities__field_indices_by_name,
  1,  ue_capabilities__number_ranges,
  (ProtobufCMessageInit) ue_capabilities__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scell_config__field_descriptors[5] =
{
  {
    "cc_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ScellConfig, has_cc_id),
    offsetof(ScellConfig, cc_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scell_index",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ScellConfig, has_scell_index),
    offsetof(ScellConfig, scell_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "use_ccs",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ScellConfig, has_use_ccs),
    offsetof(ScellConfig, use_ccs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sched_cell_index",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ScellConfig, has_sched_cell_index),
    offsetof(ScellConfig, sched_cell_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pdsch_start",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ScellConfig, has_pdsch_start),
    offsetof(ScellConfig, pdsch_start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scell_config__field_indices_by_name[] = {
  0,   /* field[0] = cc_id */
  4,   /* field[4] = pdsch_start */
  1,   /* field[1] = scell_index */
  3,   /* field[3] = sched_cell_index */
  2,   /* field[2] = use_ccs */
};
static const ProtobufCIntRange scell_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor scell_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scell_config",
  "ScellConfig",
  "ScellConfig",
  "",
  sizeof(ScellConfig),
  5,
  scell_config__field_descriptors,
  scell_config__field_indices_by_name,
  1,  scell_config__number_ranges,
  (ProtobufCMessageInit) scell_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ue_phy_config__field_descriptors[3] =
{
  {
    "sr_conf",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UePhyConfig, sr_conf),
    &sr_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transmission_mode",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UePhyConfig, has_transmission_mode),
    offsetof(UePhyConfig, transmission_mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ue_trx_antenna",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(UePhyConfig, has_ue_trx_antenna),
    offsetof(UePhyConfig, ue_trx_antenna),
    &ue_transmission_antenna__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ue_phy_config__field_indices_by_name[] = {
  0,   /* field[0] = sr_conf */
  1,   /* field[1] = transmission_mode */
  2,   /* field[2] = ue_trx_antenna */
};
static const ProtobufCIntRange ue_phy_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ue_phy_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ue_phy_config",
  "UePhyConfig",
  "UePhyConfig",
  "",
  sizeof(UePhyConfig),
  3,
  ue_phy_config__field_descriptors,
  ue_phy_config__field_indices_by_name,
  1,  ue_phy_config__number_ranges,
  (ProtobufCMessageInit) ue_phy_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ue_mac_config__field_descriptors[6] =
{
  {
    "time_alignment_timer",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeMacConfig, has_time_alignment_timer),
    offsetof(UeMacConfig, time_alignment_timer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tti_bundling",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeMacConfig, has_tti_bundling),
    offsetof(UeMacConfig, tti_bundling),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_HARQ_tx",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeMacConfig, has_max_harq_tx),
    offsetof(UeMacConfig, max_harq_tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ack_nack_simultaneous_trans",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeMacConfig, has_ack_nack_simultaneous_trans),
    offsetof(UeMacConfig, ack_nack_simultaneous_trans),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "simultaneous_ack_nack_cqi",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeMacConfig, has_simultaneous_ack_nack_cqi),
    offsetof(UeMacConfig, simultaneous_ack_nack_cqi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aper_cqi_rep",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(UeMacConfig, has_aper_cqi_rep),
    offsetof(UeMacConfig, aper_cqi_rep),
    &aperiodic_cqi_report_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ue_mac_config__field_indices_by_name[] = {
  3,   /* field[3] = ack_nack_simultaneous_trans */
  5,   /* field[5] = aper_cqi_rep */
  2,   /* field[2] = max_HARQ_tx */
  4,   /* field[4] = simultaneous_ack_nack_cqi */
  0,   /* field[0] = time_alignment_timer */
  1,   /* field[1] = tti_bundling */
};
static const ProtobufCIntRange ue_mac_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor ue_mac_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ue_mac_config",
  "UeMacConfig",
  "UeMacConfig",
  "",
  sizeof(UeMacConfig),
  6,
  ue_mac_config__field_descriptors,
  ue_mac_config__field_indices_by_name,
  1,  ue_mac_config__number_ranges,
  (ProtobufCMessageInit) ue_mac_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ue_rrc_config__field_descriptors[19] =
{
  {
    "drx_conf",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UeRrcConfig, drx_conf),
    &drx_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "meas_gap_patt",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(UeRrcConfig, has_meas_gap_patt),
    offsetof(UeRrcConfig, meas_gap_patt),
    &meas_gap_pattern__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "meas_gap_config_sf_offset",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeRrcConfig, has_meas_gap_config_sf_offset),
    offsetof(UeRrcConfig, meas_gap_config_sf_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sps_conf",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UeRrcConfig, sps_conf),
    &sps_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cqi_conf",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UeRrcConfig, cqi_conf),
    &cqi_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ue_aggreg_max_bitrate_UL",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(UeRrcConfig, has_ue_aggreg_max_bitrate_ul),
    offsetof(UeRrcConfig, ue_aggreg_max_bitrate_ul),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ue_aggreg_max_bitrate_DL",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(UeRrcConfig, has_ue_aggreg_max_bitrate_dl),
    offsetof(UeRrcConfig, ue_aggreg_max_bitrate_dl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "capabilities",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UeRrcConfig, capabilities),
    &ue_capabilities__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "beta_offset_ACK_index",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeRrcConfig, has_beta_offset_ack_index),
    offsetof(UeRrcConfig, beta_offset_ack_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "beta_offset_RI_index",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeRrcConfig, has_beta_offset_ri_index),
    offsetof(UeRrcConfig, beta_offset_ri_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "beta_offset_CQI_index",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeRrcConfig, has_beta_offset_cqi_index),
    offsetof(UeRrcConfig, beta_offset_cqi_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scell_conf",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(UeRrcConfig, n_scell_conf),
    offsetof(UeRrcConfig, scell_conf),
    &scell_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scell_deactivation_timer",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeRrcConfig, has_scell_deactivation_timer),
    offsetof(UeRrcConfig, scell_deactivation_timer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tdd_ack_nack_feedb",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(UeRrcConfig, has_tdd_ack_nack_feedb),
    offsetof(UeRrcConfig, tdd_ack_nack_feedb),
    &tdd_ack_nack_feedback_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ack_nack_rep_factor",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeRrcConfig, has_ack_nack_rep_factor),
    offsetof(UeRrcConfig, ack_nack_rep_factor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extended_bsr_size",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeRrcConfig, has_extended_bsr_size),
    offsetof(UeRrcConfig, extended_bsr_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ca_support",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeRrcConfig, has_ca_support),
    offsetof(UeRrcConfig, ca_support),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cross_carrier_sched_supp",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeRrcConfig, has_cross_carrier_sched_supp),
    offsetof(UeRrcConfig, cross_carrier_sched_supp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pcell_cc_id",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeRrcConfig, has_pcell_cc_id),
    offsetof(UeRrcConfig, pcell_cc_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ue_rrc_config__field_indices_by_name[] = {
  14,   /* field[14] = ack_nack_rep_factor */
  8,   /* field[8] = beta_offset_ACK_index */
  10,   /* field[10] = beta_offset_CQI_index */
  9,   /* field[9] = beta_offset_RI_index */
  16,   /* field[16] = ca_support */
  7,   /* field[7] = capabilities */
  4,   /* field[4] = cqi_conf */
  17,   /* field[17] = cross_carrier_sched_supp */
  0,   /* field[0] = drx_conf */
  15,   /* field[15] = extended_bsr_size */
  2,   /* field[2] = meas_gap_config_sf_offset */
  1,   /* field[1] = meas_gap_patt */
  18,   /* field[18] = pcell_cc_id */
  11,   /* field[11] = scell_conf */
  12,   /* field[12] = scell_deactivation_timer */
  3,   /* field[3] = sps_conf */
  13,   /* field[13] = tdd_ack_nack_feedb */
  6,   /* field[6] = ue_aggreg_max_bitrate_DL */
  5,   /* field[5] = ue_aggreg_max_bitrate_UL */
};
static const ProtobufCIntRange ue_rrc_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 19 }
};
const ProtobufCMessageDescriptor ue_rrc_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ue_rrc_config",
  "UeRrcConfig",
  "UeRrcConfig",
  "",
  sizeof(UeRrcConfig),
  19,
  ue_rrc_config__field_descriptors,
  ue_rrc_config__field_indices_by_name,
  1,  ue_rrc_config__number_ranges,
  (ProtobufCMessageInit) ue_rrc_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ue_config__field_descriptors[4] =
{
  {
    "rnti",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(UeConfig, has_rnti),
    offsetof(UeConfig, rnti),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phy_conf",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UeConfig, phy_conf),
    &ue_phy_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac_conf",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UeConfig, mac_conf),
    &ue_mac_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rrc_conf",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UeConfig, rrc_conf),
    &ue_rrc_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ue_config__field_indices_by_name[] = {
  2,   /* field[2] = mac_conf */
  1,   /* field[1] = phy_conf */
  0,   /* field[0] = rnti */
  3,   /* field[3] = rrc_conf */
};
static const ProtobufCIntRange ue_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ue_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ue_config",
  "UeConfig",
  "UeConfig",
  "",
  sizeof(UeConfig),
  4,
  ue_config__field_descriptors,
  ue_config__field_indices_by_name,
  1,  ue_config__number_ranges,
  (ProtobufCMessageInit) ue_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ue_config_reply__field_descriptors[1] =
{
  {
    "ue_conf",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(UeConfigReply, n_ue_conf),
    offsetof(UeConfigReply, ue_conf),
    &ue_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ue_config_reply__field_indices_by_name[] = {
  0,   /* field[0] = ue_conf */
};
static const ProtobufCIntRange ue_config_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ue_config_reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ue_config_reply",
  "UeConfigReply",
  "UeConfigReply",
  "",
  sizeof(UeConfigReply),
  1,
  ue_config_reply__field_descriptors,
  ue_config_reply__field_indices_by_name,
  1,  ue_config_reply__number_ranges,
  (ProtobufCMessageInit) ue_config_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor configs__field_descriptors[5] =
{
  {
    "enb_conf_req",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Configs, config_msg_case),
    offsetof(Configs, enb_conf_req),
    &enb_config_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enb_conf_repl",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Configs, config_msg_case),
    offsetof(Configs, enb_conf_repl),
    &enb_config_reply__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ue_conf_req",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Configs, config_msg_case),
    offsetof(Configs, ue_conf_req),
    &ue_config_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ue_conf_repl",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Configs, config_msg_case),
    offsetof(Configs, ue_conf_repl),
    &ue_config_reply__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    100,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Configs, has_type),
    offsetof(Configs, type),
    &config_msg_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned configs__field_indices_by_name[] = {
  1,   /* field[1] = enb_conf_repl */
  0,   /* field[0] = enb_conf_req */
  4,   /* field[4] = type */
  3,   /* field[3] = ue_conf_repl */
  2,   /* field[2] = ue_conf_req */
};
static const ProtobufCIntRange configs__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 100, 4 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor configs__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "configs",
  "Configs",
  "Configs",
  "",
  sizeof(Configs),
  5,
  configs__field_descriptors,
  configs__field_indices_by_name,
  2,  configs__number_ranges,
  (ProtobufCMessageInit) configs__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue config_msg_type__enum_values_by_number[4] =
{
  { "ENB_CONF_REQUEST", "CONFIG_MSG_TYPE__ENB_CONF_REQUEST", 0 },
  { "ENB_CONF_REPLY", "CONFIG_MSG_TYPE__ENB_CONF_REPLY", 1 },
  { "UE_CONF_REQUEST", "CONFIG_MSG_TYPE__UE_CONF_REQUEST", 2 },
  { "UE_CONF_REPLY", "CONFIG_MSG_TYPE__UE_CONF_REPLY", 3 },
};
static const ProtobufCIntRange config_msg_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex config_msg_type__enum_values_by_name[4] =
{
  { "ENB_CONF_REPLY", 1 },
  { "ENB_CONF_REQUEST", 0 },
  { "UE_CONF_REPLY", 3 },
  { "UE_CONF_REQUEST", 2 },
};
const ProtobufCEnumDescriptor config_msg_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "config_msg_type",
  "config_msg_type",
  "ConfigMsgType",
  "",
  4,
  config_msg_type__enum_values_by_number,
  4,
  config_msg_type__enum_values_by_name,
  1,
  config_msg_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue hopping_mode__enum_values_by_number[2] =
{
  { "HM_INTER", "HOPPING_MODE__HM_INTER", 0 },
  { "HM_INTERINTRA", "HOPPING_MODE__HM_INTERINTRA", 1 },
};
static const ProtobufCIntRange hopping_mode__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex hopping_mode__enum_values_by_name[2] =
{
  { "HM_INTER", 0 },
  { "HM_INTERINTRA", 1 },
};
const ProtobufCEnumDescriptor hopping_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "hopping_mode",
  "hopping_mode",
  "HoppingMode",
  "",
  2,
  hopping_mode__enum_values_by_number,
  2,
  hopping_mode__enum_values_by_name,
  1,
  hopping_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue phich_resource__enum_values_by_number[4] =
{
  { "PR_ONE_SIXTH", "PHICH_RESOURCE__PR_ONE_SIXTH", 0 },
  { "PR_HALF", "PHICH_RESOURCE__PR_HALF", 1 },
  { "PR_ONE", "PHICH_RESOURCE__PR_ONE", 2 },
  { "PR_TWO", "PHICH_RESOURCE__PR_TWO", 3 },
};
static const ProtobufCIntRange phich_resource__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex phich_resource__enum_values_by_name[4] =
{
  { "PR_HALF", 1 },
  { "PR_ONE", 2 },
  { "PR_ONE_SIXTH", 0 },
  { "PR_TWO", 3 },
};
const ProtobufCEnumDescriptor phich_resource__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "phich_resource",
  "phich_resource",
  "PhichResource",
  "",
  4,
  phich_resource__enum_values_by_number,
  4,
  phich_resource__enum_values_by_name,
  1,
  phich_resource__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue phich_duration__enum_values_by_number[2] =
{
  { "PHICH_DUR_NORMAL", "PHICH_DURATION__PHICH_DUR_NORMAL", 0 },
  { "PHICH_DUR_EXTENDED", "PHICH_DURATION__PHICH_DUR_EXTENDED", 1 },
};
static const ProtobufCIntRange phich_duration__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex phich_duration__enum_values_by_name[2] =
{
  { "PHICH_DUR_EXTENDED", 1 },
  { "PHICH_DUR_NORMAL", 0 },
};
const ProtobufCEnumDescriptor phich_duration__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "phich_duration",
  "phich_duration",
  "PhichDuration",
  "",
  2,
  phich_duration__enum_values_by_number,
  2,
  phich_duration__enum_values_by_name,
  1,
  phich_duration__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ul_cyclic_prefix_length__enum_values_by_number[2] =
{
  { "UL_PREFIX_NORMAL", "UL_CYCLIC_PREFIX_LENGTH__UL_PREFIX_NORMAL", 0 },
  { "UL_PREFIX_EXTENDED", "UL_CYCLIC_PREFIX_LENGTH__UL_PREFIX_EXTENDED", 1 },
};
static const ProtobufCIntRange ul_cyclic_prefix_length__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex ul_cyclic_prefix_length__enum_values_by_name[2] =
{
  { "UL_PREFIX_EXTENDED", 1 },
  { "UL_PREFIX_NORMAL", 0 },
};
const ProtobufCEnumDescriptor ul_cyclic_prefix_length__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ul_cyclic_prefix_length",
  "ul_cyclic_prefix_length",
  "UlCyclicPrefixLength",
  "",
  2,
  ul_cyclic_prefix_length__enum_values_by_number,
  2,
  ul_cyclic_prefix_length__enum_values_by_name,
  1,
  ul_cyclic_prefix_length__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue dl_cyclic_prefix_length__enum_values_by_number[2] =
{
  { "DL_PREFIX_NORMAL", "DL_CYCLIC_PREFIX_LENGTH__DL_PREFIX_NORMAL", 0 },
  { "DL_PREFIX_EXTENDED", "DL_CYCLIC_PREFIX_LENGTH__DL_PREFIX_EXTENDED", 1 },
};
static const ProtobufCIntRange dl_cyclic_prefix_length__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex dl_cyclic_prefix_length__enum_values_by_name[2] =
{
  { "DL_PREFIX_EXTENDED", 1 },
  { "DL_PREFIX_NORMAL", 0 },
};
const ProtobufCEnumDescriptor dl_cyclic_prefix_length__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "dl_cyclic_prefix_length",
  "dl_cyclic_prefix_length",
  "DlCyclicPrefixLength",
  "",
  2,
  dl_cyclic_prefix_length__enum_values_by_number,
  2,
  dl_cyclic_prefix_length__enum_values_by_name,
  1,
  dl_cyclic_prefix_length__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue duplex_mode__enum_values_by_number[2] =
{
  { "DM_TDD", "DUPLEX_MODE__DM_TDD", 0 },
  { "DM_FDD", "DUPLEX_MODE__DM_FDD", 1 },
};
static const ProtobufCIntRange duplex_mode__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex duplex_mode__enum_values_by_name[2] =
{
  { "DM_FDD", 1 },
  { "DM_TDD", 0 },
};
const ProtobufCEnumDescriptor duplex_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "duplex_mode",
  "duplex_mode",
  "DuplexMode",
  "",
  2,
  duplex_mode__enum_values_by_number,
  2,
  duplex_mode__enum_values_by_name,
  1,
  duplex_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue qam__enum_values_by_number[2] =
{
  { "MOD_16QAM", "QAM__MOD_16QAM", 0 },
  { "MOD_64QAM", "QAM__MOD_64QAM", 1 },
};
static const ProtobufCIntRange qam__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex qam__enum_values_by_name[2] =
{
  { "MOD_16QAM", 0 },
  { "MOD_64QAM", 1 },
};
const ProtobufCEnumDescriptor qam__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "qam",
  "qam",
  "Qam",
  "",
  2,
  qam__enum_values_by_number,
  2,
  qam__enum_values_by_name,
  1,
  qam__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue meas_gap_pattern__enum_values_by_number[3] =
{
  { "MGP_GP0", "MEAS_GAP_PATTERN__MGP_GP0", 0 },
  { "MGP_GP1", "MEAS_GAP_PATTERN__MGP_GP1", 1 },
  { "MGP_OFF", "MEAS_GAP_PATTERN__MGP_OFF", 2 },
};
static const ProtobufCIntRange meas_gap_pattern__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex meas_gap_pattern__enum_values_by_name[3] =
{
  { "MGP_GP0", 0 },
  { "MGP_GP1", 1 },
  { "MGP_OFF", 2 },
};
const ProtobufCEnumDescriptor meas_gap_pattern__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meas_gap_pattern",
  "meas_gap_pattern",
  "MeasGapPattern",
  "",
  3,
  meas_gap_pattern__enum_values_by_number,
  3,
  meas_gap_pattern__enum_values_by_name,
  1,
  meas_gap_pattern__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue setup_release_action__enum_values_by_number[2] =
{
  { "SRA_SETUP", "SETUP_RELEASE_ACTION__SRA_SETUP", 0 },
  { "SRA_RELEASE", "SETUP_RELEASE_ACTION__SRA_RELEASE", 1 },
};
static const ProtobufCIntRange setup_release_action__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex setup_release_action__enum_values_by_name[2] =
{
  { "SRA_RELEASE", 1 },
  { "SRA_SETUP", 0 },
};
const ProtobufCEnumDescriptor setup_release_action__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "setup_release_action",
  "setup_release_action",
  "SetupReleaseAction",
  "",
  2,
  setup_release_action__enum_values_by_number,
  2,
  setup_release_action__enum_values_by_name,
  1,
  setup_release_action__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ue_transmission_antenna__enum_values_by_number[3] =
{
  { "UETA_NONE", "UE_TRANSMISSION_ANTENNA__UETA_NONE", 0 },
  { "UETA_OPEN_LOOP", "UE_TRANSMISSION_ANTENNA__UETA_OPEN_LOOP", 1 },
  { "UETA_CLOSED_LOOP", "UE_TRANSMISSION_ANTENNA__UETA_CLOSED_LOOP", 2 },
};
static const ProtobufCIntRange ue_transmission_antenna__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex ue_transmission_antenna__enum_values_by_name[3] =
{
  { "UETA_CLOSED_LOOP", 2 },
  { "UETA_NONE", 0 },
  { "UETA_OPEN_LOOP", 1 },
};
const ProtobufCEnumDescriptor ue_transmission_antenna__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ue_transmission_antenna",
  "ue_transmission_antenna",
  "UeTransmissionAntenna",
  "",
  3,
  ue_transmission_antenna__enum_values_by_number,
  3,
  ue_transmission_antenna__enum_values_by_name,
  1,
  ue_transmission_antenna__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue aperiodic_cqi_report_mode__enum_values_by_number[6] =
{
  { "ACRM_RM12", "APERIODIC_CQI_REPORT_MODE__ACRM_RM12", 0 },
  { "ACRM_RM20", "APERIODIC_CQI_REPORT_MODE__ACRM_RM20", 1 },
  { "ACRM_RM22", "APERIODIC_CQI_REPORT_MODE__ACRM_RM22", 2 },
  { "ACRM_RM30", "APERIODIC_CQI_REPORT_MODE__ACRM_RM30", 3 },
  { "ACRM_RM31", "APERIODIC_CQI_REPORT_MODE__ACRM_RM31", 4 },
  { "ACRM_NONE", "APERIODIC_CQI_REPORT_MODE__ACRM_NONE", 5 },
};
static const ProtobufCIntRange aperiodic_cqi_report_mode__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex aperiodic_cqi_report_mode__enum_values_by_name[6] =
{
  { "ACRM_NONE", 5 },
  { "ACRM_RM12", 0 },
  { "ACRM_RM20", 1 },
  { "ACRM_RM22", 2 },
  { "ACRM_RM30", 3 },
  { "ACRM_RM31", 4 },
};
const ProtobufCEnumDescriptor aperiodic_cqi_report_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "aperiodic_cqi_report_mode",
  "aperiodic_cqi_report_mode",
  "AperiodicCqiReportMode",
  "",
  6,
  aperiodic_cqi_report_mode__enum_values_by_number,
  6,
  aperiodic_cqi_report_mode__enum_values_by_name,
  1,
  aperiodic_cqi_report_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tdd_ack_nack_feedback_mode__enum_values_by_number[2] =
{
  { "TANFM_BUNDLING", "TDD_ACK_NACK_FEEDBACK_MODE__TANFM_BUNDLING", 0 },
  { "TANFM_MULTIPLEXING", "TDD_ACK_NACK_FEEDBACK_MODE__TANFM_MULTIPLEXING", 1 },
};
static const ProtobufCIntRange tdd_ack_nack_feedback_mode__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex tdd_ack_nack_feedback_mode__enum_values_by_name[2] =
{
  { "TANFM_BUNDLING", 0 },
  { "TANFM_MULTIPLEXING", 1 },
};
const ProtobufCEnumDescriptor tdd_ack_nack_feedback_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tdd_ack_nack_feedback_mode",
  "tdd_ack_nack_feedback_mode",
  "TddAckNackFeedbackMode",
  "",
  2,
  tdd_ack_nack_feedback_mode__enum_values_by_number,
  2,
  tdd_ack_nack_feedback_mode__enum_values_by_name,
  1,
  tdd_ack_nack_feedback_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue layer_config__enum_values_by_number[4] =
{
  { "LC_ALL", "LAYER_CONFIG__LC_ALL", 1 },
  { "LC_PHY", "LAYER_CONFIG__LC_PHY", 2 },
  { "LC_MAC", "LAYER_CONFIG__LC_MAC", 4 },
  { "LC_RRC", "LAYER_CONFIG__LC_RRC", 8 },
};
static const ProtobufCIntRange layer_config__value_ranges[] = {
{1, 0},{4, 2},{8, 3},{0, 4}
};
static const ProtobufCEnumValueIndex layer_config__enum_values_by_name[4] =
{
  { "LC_ALL", 0 },
  { "LC_MAC", 2 },
  { "LC_PHY", 1 },
  { "LC_RRC", 3 },
};
const ProtobufCEnumDescriptor layer_config__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "layer_config",
  "layer_config",
  "LayerConfig",
  "",
  4,
  layer_config__enum_values_by_number,
  4,
  layer_config__enum_values_by_name,
  3,
  layer_config__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
