/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: main.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "main.pb-c.h"
void   header__init
                     (Header         *message)
{
  static Header init_value = HEADER__INIT;
  *message = init_value;
}
size_t header__get_packed_size
                     (const Header *message)
{
  assert(message->base.descriptor == &header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t header__pack
                     (const Header *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t header__pack_to_buffer
                     (const Header *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Header *
       header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Header *)
     protobuf_c_message_unpack (&header__descriptor,
                                allocator, len, data);
}
void   header__free_unpacked
                     (Header *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   emage_msg__init
                     (EmageMsg         *message)
{
  static EmageMsg init_value = EMAGE_MSG__INIT;
  *message = init_value;
}
size_t emage_msg__get_packed_size
                     (const EmageMsg *message)
{
  assert(message->base.descriptor == &emage_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t emage_msg__pack
                     (const EmageMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &emage_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t emage_msg__pack_to_buffer
                     (const EmageMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &emage_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EmageMsg *
       emage_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EmageMsg *)
     protobuf_c_message_unpack (&emage_msg__descriptor,
                                allocator, len, data);
}
void   emage_msg__free_unpacked
                     (EmageMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &emage_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor header__field_descriptors[6] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Header, has_type),
    offsetof(Header, type),
    &msg_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vers",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Header, has_vers),
    offsetof(Header, vers),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "b_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Header, has_b_id),
    offsetof(Header, b_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "m_id",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Header, has_m_id),
    offsetof(Header, m_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Header, has_seq),
    offsetof(Header, seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "t_id",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Header, has_t_id),
    offsetof(Header, t_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned header__field_indices_by_name[] = {
  2,   /* field[2] = b_id */
  3,   /* field[3] = m_id */
  4,   /* field[4] = seq */
  5,   /* field[5] = t_id */
  0,   /* field[0] = type */
  1,   /* field[1] = vers */
};
static const ProtobufCIntRange header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "header",
  "Header",
  "Header",
  "",
  sizeof(Header),
  6,
  header__field_descriptors,
  header__field_indices_by_name,
  1,  header__number_ranges,
  (ProtobufCMessageInit) header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor emage_msg__field_descriptors[4] =
{
  {
    "head",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(EmageMsg, head),
    &header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mHello",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EmageMsg, message_case),
    offsetof(EmageMsg, mhello),
    &hello__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mStats",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EmageMsg, message_case),
    offsetof(EmageMsg, mstats),
    &statistics__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mConfs",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EmageMsg, message_case),
    offsetof(EmageMsg, mconfs),
    &configs__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned emage_msg__field_indices_by_name[] = {
  0,   /* field[0] = head */
  3,   /* field[3] = mConfs */
  1,   /* field[1] = mHello */
  2,   /* field[2] = mStats */
};
static const ProtobufCIntRange emage_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor emage_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "emage_msg",
  "EmageMsg",
  "EmageMsg",
  "",
  sizeof(EmageMsg),
  4,
  emage_msg__field_descriptors,
  emage_msg__field_indices_by_name,
  1,  emage_msg__number_ranges,
  (ProtobufCMessageInit) emage_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue msg_type__enum_values_by_number[7] =
{
  { "INVALID", "MSG_TYPE__INVALID", 0 },
  { "HELLO_REQ", "MSG_TYPE__HELLO_REQ", 1 },
  { "HELLO_REP", "MSG_TYPE__HELLO_REP", 2 },
  { "STATS_REQ", "MSG_TYPE__STATS_REQ", 3 },
  { "STATS_REP", "MSG_TYPE__STATS_REP", 4 },
  { "CONF_REQ", "MSG_TYPE__CONF_REQ", 5 },
  { "CONF_REP", "MSG_TYPE__CONF_REP", 6 },
};
static const ProtobufCIntRange msg_type__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex msg_type__enum_values_by_name[7] =
{
  { "CONF_REP", 6 },
  { "CONF_REQ", 5 },
  { "HELLO_REP", 2 },
  { "HELLO_REQ", 1 },
  { "INVALID", 0 },
  { "STATS_REP", 4 },
  { "STATS_REQ", 3 },
};
const ProtobufCEnumDescriptor msg_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MsgType",
  "MsgType",
  "MsgType",
  "",
  7,
  msg_type__enum_values_by_number,
  7,
  msg_type__enum_values_by_name,
  1,
  msg_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
